### ISSUE TITLE
IS-04 Registration API and Query API: one port or two?

### ISSUE THREAD

**Issue by garethsb-sony** [bbc/nmos-testing#10]
IS0402Test custom tests are written to work with separate ``reg_url`` and ``query_url``., but GenericTest assumes both ``apis`` are on the same ``base_url`` and the web-app UI and nmos-test driver assume Registration API and Query API are served on the same port.

Is it best practice to serve Reg and Query APIs on the same port?
And does the same go for Node API and Connection API?

**Comment by andrewbonney** [comment]
I'd suggest it's best practice for any HTTP API to be served from port 80 (or 443), however that's a more general comment rather than something specific to these APIs.

The test framework should support different base URLs for each, so GenericTest will need to be modified.

**Comment by andrewbonney** [comment]
@garethsb-sony could you have a scan of https://github.com/bbc/nmos-testing/pull/13 when you get chance? I'd like to get a quick review before I merge it in as it's a larger change.
