### ISSUE TITLE
Feature request: Limit tests to run

### ISSUE THREAD

**Issue by billt-hlit** [bbc/nmos-testing#3]
Hi, Andrew,

I'd like to limit the tests run to a single test (since it's the one I'm trying to debug). Any suggestions on how I might do that, other than simply ripping out all the other tests?

Thanks,
Bill

**Comment by andrewbonney** [comment]
At present that may be the simplest approach, but I like the idea. The challenge may be that some of the tests share data so have some interdependency, but it might be possible to resolve that with some refactoring. I'll see what I can do next week.

**Comment by billt-hlit** [comment]
A related difficulty: The test numbers in the source code don't match the test numbers on the test results web page. Do you think you can rectify that in the process of your refactoring?

**Comment by andrewbonney** [comment]
I can probably do something about that. The 'basic' tests produce an unknown number of tests as they depend upon what's in the RAML. As these come up first they offset everything by a number that's only known at runtime.

I suspect if I just differentiate between these basic tests and other manually written ones in the UI then it should clear it up.

**Comment by garethsb-sony** [comment]
For me, in the results page, the Test column is always just filled with the number 1 repeated in every row. @andrewbonney thinks that may be a Jinja2 issue in some way related to https://github.com/pallets/jinja/issues/641. I've just checked and I have Jinja2 version 2.10.

**Comment by andrewbonney** [comment]
There's a starting point for this here: https://github.com/bbc/nmos-testing/tree/issue3

I'll try and finish it off next week, but I'm out of time for today. Note if you try it out that it's incomplete (the best example at present is in the IS-05 tests). It also won't currently do anything clever to deal with tests which share common setup (ie. have interdependency). I'll aim to resolve both of those before creating a proper PR against master.

**Comment by andrewbonney** [comment]
This is now available via https://github.com/bbc/nmos-testing/pull/22. Reviews appreciated.
