### ISSUE TITLE
resource ID mismatch between node and registry does not cause test failure

### ISSUE THREAD

**Issue by billt-hlit** [bbc/nmos-testing#47]
Hi, Andrew,

I'm using ea91716700cd068d769d81eb85afcc4b5dbc6f80 and noticed a bug in check_matching_resource: It doesn't return if it finds a resource ID on the node that isn't in the registry. Fix with:

    diff --git IS0401Test.py IS0401Test.py
    index b8cd8bf..91fd6a1 100644
    --- IS0401Test.py
    +++ IS0401Test.py
    @@ -164,7 +164,7 @@ class IS0401Test(GenericTest):
     
                         for resource in node_resources:
                             if resource not in reg_resources:
    -                            test.FAIL("{} {} was not found in the registry.".format(res_type.title(), resource))
    +                            return test.FAIL("{} {} was not found in the registry.".format(res_type.title(), resource))
                             elif reg_resources[resource] != node_resources[resource]:
                                 return test.FAIL("Node API JSON does not match data in registry for "
                                                  "{} {}.".format(res_type.title(), resource))

**Comment by andrewbonney** [comment]
Thanks Bill. Fixed in https://github.com/bbc/nmos-testing/commit/7cae5d8e05df006a0031a3e39e16511e9685efb3
