### ISSUE TITLE
Feature request: Report test execution times

### ISSUE THREAD

**Issue by billt-hlit** [bbc/nmos-testing#49]
Can you please add a column to indicate how long each test took? Some tests are being very slow for me (this doesn't surprise me), but it would be helpful to know which ones are the slow ones.

**Comment by andrewbonney** [comment]
Hopefully that commit will do the job :)

**Comment by garethsb-sony** [comment]
LGTM. However, it demonstrates there's something funny going on. Running the IS-04 Registry API tests against my implementation takes 1m27 before the results page appears, but the total of all the elapsed times is about 5.5 seconds.

**Comment by andrewbonney** [comment]
Interesting... Can you see on the command line when this is happening whether it gets into printing out the specific tests it's running quickly or if it takes a minute or so to start doing that?

**Comment by garethsb-sony** [comment]
Did I mention the sample size of 1? 😳

Subsequent runs have taken about 17s total, which includes a 10s wait for the first "Running basic API tests" message on the console.

This isn't the only time I've seen a run take a long time, so now I need to go and find out how to repro!!

**Comment by andrewbonney** [comment]
The most likely cause is to do with the git interactions as if you're testing a different spec or a different version it will have to jump around a little more in order to get ready. Ideally I'd like to be able to put a progress bar on screen as this happens and the tests run, but I've not looked into how that might work quite yet.

**Comment by garethsb-sony** [comment]
Makes sense. Thanks, Andrew. I'll add some logging around the git checkout so next time I get a really long run I can confirm!

**Comment by billt-hlit** [comment]
Wild idea: Make fetching the schemas the first of the auto unit tests and then its time will be reported like the other tests.
